import 'package:get/get.dart';

class LocalString extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        'en': {
          "hello": "Hello, How are you?",
          "title_sp_selec": "I'm Service Provider",
          "title_cus_selec": "I'm Customer",
          "fotter_sp_selec": "I'm Customer",
          "fotter_cus_selec": "I'm Customer",
          "title_apply_filter": "Apply Filter",
          "btn_apply": "Apply",
          "select_address": "Select Address",
          "title_custom_search_filter": "Search With Filter",
          "select_skills": "Select Skills",
          "btn_reset": "Reset",
          "categories": "Categories",
          "view_all": "View All",
          "featured_services": "Featured Services",
          "top_rated_professionals": "Top Rated Professionals",
          "app_bar_cust_profile": "Customer Profile",
          "nav_home": "Home",
          "nav_Profile": "Profile",
          "nav_job_manager": "Job Manager",
          "nav_job_conversatin": "Conversation",
          "nav_my_account": "My Account",
          "title_my_acount_info": "Account info,Setting more",
          "general": "General",
          "change_language": "Change Language",
          "notification": "Notfications",
          "about_odlay_service": "About Odlay Services",
          "privacy_policy": "Privacy Policy",
          "help_support": "Help Support & tutorials",
          "rate_odlay": "Rate Odlay Services",
          "payment": "Payment",
          "wallet": "Wallet",
          "wallet_method": "Wallet Method",
          "signout": "Sign Out",
          "delete_my_account": "Delete My Account",
          "disable_my_account": "Disable My Account",
          "app_bar_my_wallet": "My Wallet",
          "completed_job": "Completed Jobs",
          "total_spending": "Total Spendings",
          "total_earnings": "Total Earnings",
          "cash_payment": "Cash Payment",
          "online_payment": "Online Payment",
          "payment_date": "Payment Date:",
          "bid_amount_wallet": "Bid Amount:",
          "odlay_fee_wallet": "Odlay Fee:",
          "amount_payable": "Amount Payable:",
          "by_card": "By Card",
          "created_at": "Created At:",
          "job_deadline": "Job Deadline:",
          "budget": "Budget",
          "applicant_list": "Applicant list:",
          "invite_service_provider": "Invite Top Service Providers",
          "delete_job_title": "Delete Job",
          "delete_job_meeage": "Are you sure you want Delete this Job!",
          "delete_job_postive_btn": "Yes",
          "bid_amount": "Bid Amount",
          "odlay_fee": "Odlay Fee",
          "total_payable_amount": "Total Payable Amount",
          "no_of_days": "No of Days",
          "number_of_recomended": "No Recomended Providers Found",
          "invited": "Invited",
          "chat": "Chat",
          "call": "Call",
          "fully_verfied": "fully Verfied",
          "partially_verfied": "partially Verfied",
          "expert": "Expert",
          "skills": "Skills",
          "location": "Location",
          "job_budget": "Job Budget",
          "note_all_vate": "Note:All the amounts include VAT",
          "updating": "Updating",
          "award": "Award",
          "disclaimer": "Disclaimer",
          "decline": "Decline",
          "accept": "Accept",
          "decline": "Decline",
          "your_location_permission": "Your Location Permission",
          "your_location_h1":
              "To use your location to automatically see the latest jobs or service providers around your area, please allow Odlay Services to use your location when the application is open or running.",
          "your_location_h2":
              "Odlay Services will use your location to fetch the latest jobs or closest service providers around your area and will order them by distance from your location",
          "job_title": "Job Title",
          "job_desc": "Job Description",
          "enter_job_budget": "Enter Job Budget",
          "advance_options": "Advance options",
          "attach_images": "Attach Images",
          "post_job": "Post Job",
          "posting": "Posting",
          "post_your_service": "Post Your Service",
          "service_title": "Service Title",
          "service_desc": "Post Your Service",
          "enter_service_price": "Enter service amount",
          "your_receivable_amount": "Post Your Service",
          "post_service_btn": "Post Your Service",
          "job_detail_app_bar": "Job Detail",
          "name": "Name",
          "str_created_at": "Created At",
          "str_dealine": "Deadline",
          "str_job_images": "Job Images",
          "job_has_no_images": "Job has no Images",
          "note_address":
              "Note:Your business address is shown to the customers so they know where you work at and what is your official business address. This increases the trust of customers to work with you.",
          "add_skill": "Add Skill",
          "update": "Update",
          "updating": "Updating",
          "add_skill_Alert":
              "You do not have the required skill for this job Please add the required skills in your profile and apply for this job.\n",
          "distance": "Distance",
          "customer_budget": "Customer Budget",
          "apply_enter_job_budget": "Enter Job Budget",
          "your_receivable_amount": "Your Receivable Amount",
          "time_to_complete": "Time to complete job(in days)",
          "service_desc": "Service Description",
          "applying": "Applying",
          "tab_opne": "Open",
          "tab_started": "Started",
          "tab_closed": "Closed",
          "started_job": "Started Date:",
          "payable_amout": "Payable Amount:",
          "status": "Status",
          "created_date": "Created Date",
          "rewarded_to": "Rewarded To",
          "receivable_amount": "Receivable Amount (inc VAT):",

          "you_will_receive": "You Will receive",
          "payment_method_str": "Payment Method",
          "wellcome_to_odlay": "Wellcome to Odlay Services",
          "privacy_policy_paragraph":
              "Odlay Services is a mobile platform that connects consumers with local experts & service providers. Consumers can easily find the local services by searching for the needed experts or posting their needs and get multiple offers from the relevant Service Providers.\n\nThe app also helps experts, skilled &amp; nonskilled workers, freelancers, and various job seekers to find jobs quickly and get regular requests for work.\n\nIn order to use the Odlay Services platform, please agree that your data will be processed according to Odlay Services Privacy Policy. Please also read the User Terms and Conditions which contains the usage policy, licensing, expected behavior of the platform, conditions, and other terms, under which the platform can be used.\n\nNon of the Service Providers are directly affiliated with us. Odlay Services only provides a platform for connecting service providers with experts. For detailed EULA & Terms and Conditions, please click the relevant links below to read further and get further information. If there are still any questions, please feel free to write an email or us or reach out to us on our facebook page.",
          "agree_terms_conditions":
              "I have read and agree with User Terms of Odlay Services",
          "agree_privacy_conditions":
              "I have read and agree with Privacy Policy of Odlay Services",
          "tab_profile": "Profile",
          "tab_my_service": "My Services",
          "available_on_phone": "Available on phone",
          "skill_sp": "Skills",
          "add_your_work_images": "Add your work images",
          "review_sp": "Reviews",
          "sheet_edit_profile_title": "Edit Profile",
          "add_portfolio_images_title_sheet": "Add Portfolio Images",
          "lates_posted_job": "Latest posted job",
          "btn_post_service": "Post New Service",
          "search_by_b_name": "Search by name or business name",
          "please_update_address": "Please update business/work address",
          "please_add_portfolio_images": "Please add portfolio images",
          "visit_sp_tab_name_profile": "Service Provider Profile",
          "visit_sp_tab_name_services": "Fixed Price Services",
          "str_hire": "Hire",
          "str_chat": "Chat",
          "str_call": "Call",
          "str_portfolio": "Portfolio",
          "str_no_portfolio": "No portfolio images are available",
          "str_direct_hire": "Direct Hire",
          "str_date_d_hire": "Date:",
          "str_skills_d_hire": "Skills:",
          "str_invite": "Invite",
          "str_invited": "Invited",
          "str_detail": "Detail",
          "str_enter_address": "Enter Address",
          "str_select_date": "Select Date",
          "str_drop_male": "Male",
          "str_drop_female": "Female",
          "str_drop_any": "Any",
          "str_btn_payment": "Payment",
          "str_payment_method": "payment Method",
          "str_btn_invit_top_rated": "Invite Top Service Providers",
          "str_my_wallet": "My Wallet",
          "str_my_cus_inprogress_jobs": "InProgreess Jobs",
          "str_my_cus_un_released_payment": "Unreleased Payment",
          "str_my_cus_completed_jobs": "Completed Job",
          "str_my_cus_total_spendings": "Total Spendings",
          "str_my_cus_cash_payment": "Cash payments",
          "str_my_cus_online_payment": "Online Payments",
          "str_my_cus_patment_date": "Payment Date:",
          "str_my_cus_bid_amount": "Bid Amount:",
          "str_my_cus_odlay_fee": "Odlay Fee:",
          "str_my_cus_amount_payable": "Amount Payable:",
          "str_sp_with_drawn_earnings": "Unwithdrawn Earnings",
          "str_sp_odlay_fee_on_cash": "Odlay Fee On Cash Earnings",
          "str_my_sp_total_earnigns": "Total Earnings",
          "str_my_sp_amount_receivable": "Amount Receivable:",
          "str_cancel": "Cancel",
          "str_radio_open_job": "Open Job",
          "str_radio_private_job": "Private Job",
          "str_hiring": "Hiring",
          "str_applying": "Applying",
          "str_apply_amoutn": "Enter Amount in",
          "str_btn_award": "Award",
          "str_title_sheet_edit_proposal": "Update Bid Amount",
          "btn_start": "Start",
          "title_disclaimer": "Disclaimer",
          "enter_bid_amount": "Enter bid amount",
          "str_cancel_this_job": "Cancel this job",
          "sp_bid_amount_message": "The bid amount includes odlay platform fee and VAT",
          "mark_complete": "Mark Complete",
          "mark_not_complete": "Work Not Completed",
          "btn_sp_complete": "Complete",
          "btn_dispute": "Dispute",
          "review_sheet_title": "Provider Feedback for this service Provider",
          "review_desc": "Review Description",
          "review_btn_submitting": "Submitting...",
          "review_btn_submitt": "Submit",
          "receibal_amount_whill_applying": "Your Receivable Amount (inc VAT)",

        },
        'fi': {
          "hello": "Hello, How are you?",
          "title_sp_selec": "Olen Palveluntarjoaja",
          "title_cus_selec": "Olen Asiakas",
          "fotter_sp_selec": "Olen Asiakas",
          "fotter_cus_selec": "Olen Asiakas",
          "title_apply_filter": "Käytä suodatinta",
          "btn_apply": "Käytä",
          "select_address": "Valitse Osoite",
          "title_custom_search_filter": "Hae suodattimella",
          "select_skills": "Valitse Taidot",
          "btn_reset": "Nollaa",
          "categories": "Luokat",
          "view_all": "Näytä kaikki",
          "featured_services": "Suositellut palvelut",
          "top_rated_professionals": "Parhaiksi arvioidut ammattilaiset",
          "app_bar_cust_profile": "Asiakas profiili",
          "nav_home": "Koti",
          "nav_Profile": "Profiili",
          "nav_job_manager": "Työpäällikkö",
          "nav_job_conversatin": "Keskustelu",
          "nav_my_account": "Tilini",
          "title_my_acount_info": "Tilitiedot, lisäasetukset",
          "general": "KenraaliGeneral",
          "change_language": "Change Language",
          "notification": "Vaihda kieltä",
          "about_odlay_service": "Tietoja Odlay-palveluista",
          "privacy_policy": "Privacy Policy",
          "help_support": "Ohje Tuki ja opetusohjelmat",
          "rate_odlay": "Arvioi Odlay-palvelut",
          "payment": "Maksu",
          "wallet": "Lompakko",
          "wallet_method": "Lompakkomenetelmä",
          "signout": "Kirjaudu ulos",
          "delete_my_account": "Poista minun tilini",
          "disable_my_account": "Poista Oma tili käytöstä",
          "app_bar_my_wallet": "Lompakkoni",
          "completed_job": "Valmiit työt",
          "total_spending": "Kokonaiskulut",
          "total_earnings": "kokonaistulot",
          "cash_payment": "Käteismaksu",
          "online_payment": "Online Maksu",
          "payment_date": "Maksupäivä:",
          "bid_amount_wallet": "Tarjoussumma:",
          "odlay_fee_wallet": "Odlay-maksu:",
          "amount_payable": "Maksettava summa:",
          "by_card": "Kortilla",
          "created_at": "Luotu osoitteessa:",
          "job_deadline": "Työn määräaika:",
          "budget": "Budjetti",
          "applicant_list": "Hakijaluettelo:",
          "invite_service_provider": "Kutsu parhaat palveluntarjoajat",
          "delete_job_title": "Poista työ",
          "delete_job_meeage": "Haluatko varmasti poistaa tämän työn!",
          "delete_job_postive_btn": "Joo",
          "bid_amount": "Tarjoussumma",
          "odlay_fee": "Odlay-maksu",
          "total_payable_amount": "Maksettava kokonaissumma",
          "no_of_days": "Päivien lukumäärä",
          "number_of_recomended": "Suositeltuja palveluntarjoajia ei löytynyt",
          "invited": "Kutsuttu",
          "chat": "Chat",
          "call": "Soittaa puhelimella",
          "fully_verfied": "täysin varmistettu",
          "partially_verfied": "osittain varmistettu",
          "expert": "Asiantuntija",
          "skills": "Taidot",
          "location": "Sijainti",
          "job_budget": "Työn budjetti",
          "note_all_vate": "Huomaa: Kaikki summat sisältävät ALV:n",
          "updating": "Päivitetään",
          "award": "Myöntää",
          "disclaimer": "Vastuuvapauslauseke",
          "decline": "Hylkää",
          "accept": "Hyväksyä",
          "decline": "Hylkää",
          "your_location_permission": "Sijaintilupasi",
          "your_location_h1":
              "Jos haluat käyttää sijaintiasi nähdäksesi automaattisesti uusimmat työpaikat tai palveluntarjoajat alueellasi, anna Odlay Services käyttää sijaintiasi, kun sovellus on auki tai käynnissä.",
          "your_location_h2":
              "Odlay Services käyttää sijaintiasi uusimpien työpaikkojen tai lähimpien palveluntarjoajien hakemiseen alueellasi ja tilaa ne etäisyyden mukaan sijainnistasi",
          "job_title": "Työnimike",
          "job_desc": "Työnkuvaus",
          "enter_job_budget": "Anna työbudjetti",
          "advance_options": "Lisäasetukset",
          "attach_images": "Liitä kuvat",
          "post_job": "Lähetä työ",
          "posting": "Lähettäminen",
          "post_your_service": "Lähetä palvelusi",
          "service_title": "Palvelun nimi",
          "service_desc": "Lähetä palvelusi",
          "enter_service_price": "Lähetä palvelusi",
          "your_receivable_amount": "Lähetä palvelusi",
          "post_service_btn": "Lähetä palvelusi",
          "job_detail_app_bar": "Työn tiedot",
          "name": "Nimi",
          "str_created_at": "Luotu klo",
          "str_dealine": "Takaraja",
          "str_job_images": "Työkuvat",
          "job_has_no_images": "Työpaikalla ei ole kuvia",
          "note_address":
              "Huomautus: Yrityksesi osoitteesi näytetään asiakkaille, jotta he tietävät, missä työskentelet ja mikä on virallinen osoitteesi. Tämä lisää asiakkaiden luottamusta työskentelemään kanssasi.",
          "add_skill": "Lisää taitoa",
          "update": "Päivittää",
          "updating": "Päivitetään",
          "add_skill_Alert":
              "Sinulla ei ole tähän työhön vaadittavia taitoja. Lisää vaaditut taidot profiiliisi ja hae tätä työtä.\n",
          "distance": "Etäisyys",
          "customer_budget": "Asiakasbudjetti",
          "customer_budget": "Asiakasbudjetti",
          "apply_enter_job_budget": "Anna työbudjetti",
          "your_receivable_amount": "Saatavan summasi",
          "time_to_complete": "Aika suorittaa työ loppuun(päivissä)",
          "service_desc": "palvelun kuvaus",
          "applying": "Hakeminen",
          "tab_opne": "Avata",
          "tab_started": "Aloitettu",
          "tab_closed": "Suljettu",
          "started_job": "Aloituspäivämäärä:",
          "payable_amout": "Maksettava summa:",
          "status": "Tila",
          "created_date": "Luomispäivämäärä",
          "rewarded_to": "Palkittu vastaanottajalle",
          "receivable_amount": "Saatavien määrä:",
          "you_will_receive": "Sinä tulet vastaanottamaan",
          "payment_method_str": "Maksutapa",
          "tab_profile": "Profiili",
          "tab_my_service": "Omat palvelut",
          "available_on_phone": "Saatavilla puhelimessa",
          "skill_sp": "Taidot",
          "add_your_work_images": "Lisää työkuviasi",
          "review_sp": "Arvostelut",
          "sheet_edit_profile_title": "Muokkaa profiilia",
          "add_portfolio_images_title_sheet": "Lisää portfoliokuvia",
          "lates_posted_job": "Viimeisin julkaistu työpaikka",
          "btn_post_service": "Julkaise uusi palvelu",
          "search_by_b_name": "Hae nimellä tai yrityksen nimellä",
          "please_update_address": "Päivitä yrityksen/työpaikan osoite",
          "please_add_portfolio_images": "Lisää portfoliokuvia",
          "visit_sp_tab_name_profile": "Palveluntarjoajan profiili",
          "visit_sp_tab_name_services": "Kiinteähintaiset palvelut",
          "str_hire": "Vuokraus",
          "str_chat": "Chat",
          "str_call": "Puhelu",
          "str_portfolio": "Portfolio",
          "str_no_portfolio": "Portfoliokuvia ei ole saatavilla",
          "str_direct_hire": "Suora vuokraus",
          "str_date_d_hire": "Päivämäärä:",
          "str_skills_d_hire": "Taidot:",
          "str_invite": "Kutsu",
          "str_invited": "Kutsuttu",
          "str_detail": "Yksityiskohta",
          "str_enter_address": "Anna osoite",
          "str_select_date": "Valitse Päivämäärä",
          "str_drop_male": "Uros",
          "str_drop_female": "Nainen",
          "str_drop_any": "Minkä tahansa",
          "str_btn_payment": "Maksu",
          "str_payment_method": "maksutapa",
          "str_btn_invit_top_rated": "Kutsu parhaat palveluntarjoajat",
          "str_my_wallet": "Lompakkoni",
          "str_my_cus_inprogress_jobs": "Meneillään olevat työt",
          "str_my_cus_un_released_payment": "Julkaisematon maksu",
          "str_my_cus_completed_jobs": "Valmis työ",
          "str_my_cus_total_spendings": "Kokonaiskulut",
          "str_my_cus_cash_payment": "Käteis maksut",
          "str_my_cus_online_payment": "Verkko maksut",
          "str_my_cus_patment_date": "Maksupäivä:",
          "str_my_cus_bid_amount": "Tarjoussumma:",
          "str_my_cus_odlay_fee": "Odlay-maksu:",
          "str_my_cus_amount_payable": "Maksettava määrä:",
          "str_sp_with_drawn_earnings": "Nostamattomat tulot",
          "str_sp_odlay_fee_on_cash": "Odlay-palkkio käteistuloista",
          "str_my_sp_total_earnigns": "kokonaistulot",
          "str_my_sp_amount_receivable": "Saatava määrä:",
          "str_cancel": "Peruuttaa",
          "str_radio_open_job": "Avaa työ",
          "str_radio_private_job": "Yksityinen Työ",
          "str_hiring": "Palkkaaminen",
          "str_applying": "Hakeminen",
          "str_apply_amoutn": "Syötä summa",
          "str_btn_award": "Myöntää",
          "btn_start": "alkaa",
          "title_disclaimer": "Vastuuvapauslauseke",
          "wellcome_to_odlay": "Wellcome to Odlay Services",
          "privacy_policy_paragraph":
              "Odlay Services on mobiilialusta, joka yhdistää kuluttajat paikallisiin asiantuntijoihin ja palveluntarjoajiin. Kuluttajat voivat helposti löytää paikalliset palvelut etsimällä tarvittavia asiantuntijoita tai ilmoittamalla tarpeensa ja saada useita tarjouksia asianmukaisilta palveluntarjoajilta.\n\nSovellus auttaa myös asiantuntijoita, ammattitaitoisia ja kouluttamattomia työntekijöitä, freelancereita ja erilaisia ​​työnhakijoita löytääkseen töitä nopeasti ja saadakseen säännöllisiä työpyyntöjä.\n\nJotta käyttää Odlay Services -alustaa, hyväksy, että tietojasi käsitellään Odlay Services -tietosuojakäytännön mukaisesti. Lue myös käyttöehdot, jotka sisältävät käyttöpolitiikan, lisenssit, alustan odotetun toiminnan, ehdot ja muut ehdot, joiden mukaisesti alustaa voidaan käyttää.\n\nMikään palveluntarjoaja ei ole suoraan yhteydessä meihin. Odlay Services tarjoaa vain alustan palveluntarjoajien ja asiantuntijoiden yhdistämiseen. Yksityiskohtaiset EULA-sopimukset ja ehdot saat napsauttamalla alla olevia linkkejä lukeaksesi lisää ja saadaksesi lisätietoja. Jos sinulla on vielä kysyttävää, kirjoita meille sähköpostia tai ota meihin yhteyttä Facebook-sivullamme.",
          "enter_bid_amount": "Enter bid amount",
          "str_cancel_this_job": "Peruuta tämä työ",
          "sp_bid_amount_message": "Tarjoussumma sisältää odlay-alustamaksun ja ALV:n",
          "mark_complete": "Merkitse valmiiksi",
          "mark_not_complete": "Työtä ei ole suoritettu",
          "btn_sp_complete": "Saattaa loppuun",
          "btn_dispute": "Kiista",
          "review_sheet_title": "Palveluntarjoajan palaute tälle palveluntarjoajalle",
          "review_desc": "Tarkista kuvaus",
          "review_btn_submitting": "Lähetetään...",
          "review_btn_submitt": "Lähetä",
          "receibal_amount_whill_applying": "saatavasi summa (sis. alv)",
        },
        'ur': {
          "hello": "ہیلو آپ کیسے ہیں؟",
          "title_sp_selec": "میں سروس پرووائیڈر ہوں۔",
          "title_cus_selec": "میں گاہک ہوں۔",
          "fotter_sp_selec": "میں گاہک ہوں۔",
          "fotter_cus_selec": "میں گاہک ہوں۔",
          "title_apply_filter": "فلٹر لگائیں۔",
          "btn_apply": "درخواست دیں",
          "select_address": "پتہ منتخب کریں۔",
          "title_custom_search_filter": "فلٹر کے ساتھ تلاش کریں۔",
          "select_skills": "ہنر منتخب کریں۔",
          "btn_reset": "دوبارہ ترتیب دیں۔",
          "categories": "اقسام",
          "view_all": "سب دیکھیں",
          "featured_services": "نمایاں خدمات",
          "top_rated_professionals": "ٹاپ ریٹیڈ پروفیشنلز",
          "app_bar_cust_profile": "کسٹمر پروفائل",
          "nav_home": "ہوم",
          "nav_Profile": "پروفائل",
          "nav_job_manager": "جاب مینیجر",
          "nav_job_conversatin": "بات چیت",
          "nav_my_account": "میرا اکاونٹ",
          "title_my_acount_info": "اکاؤنٹ کی معلومات، مزید سیٹنگ",
          "general": "جنرل",
          "change_language": "زبان تبدیل کریں",
          "notification": "اطلاعات",
          "about_odlay_service": "اوڈلے سروسز کے بارے میں",
          "privacy_policy": "رازداری کی پالیسی",
          "help_support": "مدد سپورٹ اور سبق",
          "rate_odlay": "اوڈلے سروسز کی درجہ بندی کریں۔",
          "payment": "ادائیگی",
          "wallet": "پرس",
          "wallet_method": "بٹوے کا طریقہ",
          "signout": "باہر جائیں",
          "delete_my_account": "میرا اکاؤنٹ حذف کریں۔",
          "disable_my_account": "میرا اکاؤنٹ غیر فعال کریں۔",
          "app_bar_my_wallet": "میرا بٹوہ",
          "completed_job": "مکمل نوکریاں",
          "total_spending": "کل اخراجات",
          "total_earnings": "کل کمائی",
          "cash_payment": "نقد ادائیگی",
          "online_payment": "آن لائن ادائیگی",
          "payment_date": "ادائیگی کی تاریخ:",
          "bid_amount_wallet": "بولی کی رقم:",
          "odlay_fee_wallet": "اوڈلے فیس:",
          "amount_payable": "قابل ادائیگی رقم:",
          "by_card": "بذریعہ کارڈ",
          "created_at": "پر تخلیق کیا گیا:",
          "job_deadline": "ملازمت کی آخری تاریخ:",
          "budget": "بجٹ",
          "applicant_list": "درخواست دہندگان کی فہرست:",
          "invite_service_provider": "ٹاپ سروس پروایئڈر کو مدعو کریں",
          "delete_job_title": "ملازمت کو حذف کریں۔",
          "delete_job_meeage": "کیا آپ واقعی اس جاب کو حذف کرنا چاہتے ہیں!",
          "delete_job_postive_btn": "جی ہاں",
          "bid_amount": "بولی کی رقم",
          "odlay_fee": "اوڈلے فیس",
          "total_payable_amount": "کل قابل ادائیگی رقم",
          "no_of_days": "دنوں کی تعداد",
          "number_of_recomended": "کوئی تجویز کردہ فراہم کنندہ نہیں ملا",
          "invited": "مدعو کیا۔",
          "chat": "گپ شپ",
          "call": "کال کریں۔",
          "fully_verfied": "مکمل طور پر تصدیق شدہ",
          "partially_verfied": "جزوی طور پر تصدیق شدہ",
          "expert": "ماہر",
          "skills": "ہنر",
          "location": "مقام",
          "job_budget": "ملازمت کا بجٹ",
          "note_all_vate": "نوٹ: تمام رقوم میں VAT شامل ہے۔",
          "updating": "اپ ڈیٹ کر رہا ہے۔",
          "award": "ایوارڈ",
          "disclaimer": "ڈس کلیمر",
          "decline": "رد کرنا",
          "accept": "قبول کریں۔",
          "decline": "رد کرنا",
          "your_location_permission": "آپ کی جگہ کی اجازت",
          "your_location_h1":
              "اپنے علاقے کے ارد گرد تازہ ترین نوکریوں یا سروس فراہم کنندگان کو خود بخود دیکھنے کے لیے اپنا مقام استعمال کرنے کے لیے، براہ کرم Odlay سروسز کو ایپلیکیشن کے کھلے یا چلتے وقت اپنا مقام استعمال کرنے کی اجازت دیں۔",
          "your_location_h2":
              "Odlay سروسز آپ کے علاقے کے ارد گرد تازہ ترین نوکریوں یا قریبی سروس فراہم کنندگان کو لانے کے لیے آپ کے مقام کا استعمال کریں گی اور آپ کے مقام سے فاصلے کے حساب سے آرڈر کریں گی۔",
          "job_title": "کام کا عنوان",
          "job_desc": "کام کی تفصیل",
          "enter_job_budget": "ملازمت کا بجٹ درج کریں۔",
          "advance_options": "پیشگی اختیارات",
          "attach_images": "امیجز منسلک کریں۔",
          "post_job": "نوکری پوسٹ کریں۔",
          "posting": "پوسٹنگ",
          "post_your_service": "اپنی سروس پوسٹ کریں۔",
          "service_title": "سروس کا عنوان",
          "service_desc": "اپنی سروس پوسٹ کریں۔",
          "enter_service_price": "اپنی سروس پوسٹ کریں۔",
          "your_receivable_amount": "اپنی سروس پوسٹ کریں۔",
          "post_service_btn": "اپنی سروس پوسٹ کریں۔",
          "job_detail_app_bar": "ملازمت کی تفصیل",
          "name": "Name",
          "str_created_at": "پر تخلیق کیا گیا۔",
          "str_dealine": "ڈیڈ لائن",
          "str_job_images": "ملازمت کی تصاویر",
          "job_has_no_images": "نوکری کی کوئی تصویر نہیں ہے۔",
          "note_address":
              "نوٹ: آپ کا کاروباری پتہ صارفین کو دکھایا جاتا ہے تاکہ وہ جان سکیں کہ آپ کہاں کام کرتے ہیں اور آپ کا سرکاری کاروباری پتہ کیا ہے۔ اس سے آپ کے ساتھ کام کرنے کے لیے صارفین کا اعتماد بڑھتا ہے۔.",
          "add_skill": "مہارت شامل کریں۔",
          "update": "اپ ڈیٹ",
          "updating": "اپ ڈیٹ کر رہا ہے۔",
          "add_skill_Alert":
              "Yآپ کے پاس اس نوکری کے لیے مطلوبہ مہارت نہیں ہے براہ کرم اپنی پروفائل میں مطلوبہ مہارتیں شامل کریں اور اس نوکری کے لیے درخواست دیں۔\n",
          "distance": "فاصلے",
          "customer_budget": "کسٹمر بجٹ",
          "customer_budget": "کسٹمر بجٹ",
          "apply_enter_job_budget": "ملازمت کا بجٹ درج کریں۔",
          "your_receivable_amount": "آپ کی قابل وصول رقم",
          "time_to_complete": "کام مکمل کرنے کا وقت (دنوں میں)",
          "service_desc": "سروس کی تفصیل",
          "applying": "درخواست دے رہا ہے۔",
          "tab_opne": "کھولیں۔",
          "tab_started": "شروع",
          "tab_closed": "بند",
          "started_job": "شروع ہونے کی تاریخ:",
          "payable_amout": "قابل ادائیگی رقم:",
          "status": "حالت",
          "created_date": "تشکیل کی تاریخ",
          "rewarded_to": "کو انعام دیا گیا۔",
          "receivable_amount": "قابل وصول رقم:",
          "you_will_receive": "آپ کو موصول ہوجائیگا",
          "payment_method_str": "ادائیگی کا طریقہ",
          "tab_profile": "پروفائل",
          "tab_my_service": "میری خدمات",
          "available_on_phone": "فون پر دستیاب ہے۔",
          "skill_sp": "ہنر",
          "add_your_work_images": "اپنے کام کی تصاویر شامل کریں۔",
          "review_sp": "جائزے",
          "sheet_edit_profile_title": "پروفائل میں ترمیم کریں",
          "add_portfolio_images_title_sheet": "پورٹ فولیو امیجز شامل کریں۔",
          "lates_posted_job": "تازہ ترین پوسٹ کردہ نوکری",
          "btn_post_service": "نئی سروس پوسٹ کریں۔",
          "search_by_b_name": "نام یا کاروباری نام سے تلاش کریں۔",
          "please_update_address": "براہ کرم کاروبار/کام کا پتہ اپ ڈیٹ کریں۔",
          "please_add_portfolio_images":
              "براہ کرم پورٹ فولیو کی تصاویر شامل کریں۔",
          "visit_sp_tab_name_profile": "سروس پرووائیڈر پروفائل",
          "visit_sp_tab_name_services": "فکسڈ پرائس سروسز",
          "str_hire": "کرایہ پر لینا",
          "str_chat": "گپ شپ",
          "str_call": "کال کریں۔",
          "str_portfolio": "پورٹ فولیو",
          "str_no_portfolio": "کوئی پورٹ فولیو تصاویر دستیاب نہیں ہیں۔",
          "str_direct_hire": "ڈائریکٹ ہائر",
          "str_date_d_hire": "تاریخ:",
          "str_skills_d_hire": "ہنر:",
          "str_invite": "دعوت دیں۔",
          "str_invited": "مدعو کیا۔",
          "str_detail": "تفصیل",
          "str_enter_address": "ایڈریس درج کریں۔",
          "str_select_date": "تاریخ منتخب کریں۔",
          "str_drop_male": "مرد",
          "str_drop_female": "عورت",
          "str_drop_any": "کوئی اور",
          "str_btn_payment": "قیمت",
          "str_payment_method": "قیمت ادایئگی کا طریقہ",
          "str_btn_invit_top_rated": "ٹاپ کے سروس پروایئڈر کو مدعو کریں",
          "str_my_wallet": "میرا بٹوا",
          "str_my_cus_inprogress_jobs": "جاب پراگرس میں ہے",
          "str_my_cus_un_released_payment": "نان رلیز قیمت",
          "str_my_cus_completed_jobs": "ختم شد جاب",
          "str_my_cus_total_spendings": "ٹوٹل خرچ شدہ",
          "str_my_cus_cash_payment": "کیش ادائیگی",
          "str_my_cus_online_payment": "آن لائن ادائیگی",
          "str_my_cus_patment_date": " ادائیگی کی تاریخ",
          "str_my_cus_bid_amount": "بڈ رقم",
          "str_my_cus_odlay_fee": "اوڈلے کی فیس:",
          "str_my_cus_amount_payable": " قابل  ادائیگی رقم",
          "str_sp_with_drawn_earnings": "غیر منقطع آمدنی",
          "str_sp_odlay_fee_on_cash": "نقد آمدنی پر اوڈلے فیس",
          "str_my_sp_total_earnigns": "کل کمائی",
          "str_my_sp_amount_receivable": "قابل وصول رقم:",
          "str_cancel": "منسوخ کریں۔",
          "title_disclaimer": "ڈس کلیمر",
          "wellcome_to_odlay": "اوڈلے سروسز میں خوش آمدید",
          "privacy_policy_paragraph":
              "اوڈلے سروسز ایک موبائل پلیٹ فارم ہے جو صارفین کو مقامی ماہرین اور خدمات فراہم کرنے والوں سے جوڑتا ہے۔ صارفین مطلوبہ ماہرین کو تلاش کر کے یا اپنی ضروریات پوسٹ کر کے مقامی خدمات آسانی سے تلاش کر سکتے ہیں اور متعلقہ سروس فراہم کنندگان سے متعدد پیشکشیں حاصل کر سکتے ہیں۔\n\nیہ ایپ ماہرین، ہنر مند اور غیر ہنر مند کارکنان، فری لانسرز، اور مختلف ملازمت کے متلاشی افراد جلدی سے ملازمتیں تلاش کرنے اور کام کے لیے باقاعدہ درخواستیں حاصل کرنے کے لیے۔\n\nOdlay سروسز پلیٹ فارم استعمال کرنے کے لیے، براہ کرم اس بات سے اتفاق کریں کہ آپ کے ڈیٹا پر Odlay Services کی رازداری کی پالیسی کے مطابق کارروائی کی جائے گی۔ براہ کرم صارف کی شرائط و ضوابط کو بھی پڑھیں جن میں استعمال کی پالیسی، لائسنسنگ، پلیٹ فارم کا متوقع برتاؤ، شرائط اور دیگر شرائط شامل ہیں، جن کے تحت پلیٹ فارم استعمال کیا جا سکتا ہے۔\n\nسروس فراہم کرنے والے میں سے کوئی بھی براہ راست ہمارے ساتھ وابستہ نہیں ہیں۔ Odlay سروسز صرف خدمات فراہم کرنے والوں کو ماہرین کے ساتھ مربوط کرنے کے لیے ایک پلیٹ فارم مہیا کرتی ہے۔ تفصیلی EULA اور شرائط و ضوابط کے لیے، مزید پڑھنے اور مزید معلومات حاصل کرنے کے لیے براہ کرم نیچے دیے گئے متعلقہ لنکس پر کلک کریں۔ اگر اب بھی کوئی سوالات ہیں، تو براہ کرم بلا جھجھک ہمیں ای میل لکھیں یا ہمارے فیس بک پیج پر ہم سے رابطہ کریں۔",
          "enter_bid_amount": "Enter bid amount",
          "str_cancel_this_job": "Cancel this job",
          "sp_bid_amount_message": "بولی کی رقم میں اوڈلے پلیٹ فارم فیس اور VAT شامل ہے۔",
          "mark_complete": "مکمل نشان زد کریں۔",
          "mark_not_complete": "کام مکمل نہیں ہوا۔",
          "btn_sp_complete": "مکمل",
          "btn_dispute": "تنازعہ",
          "review_sheet_title": "اس سروس فراہم کنندہ کے لیے فراہم کنندہ کی رائے",
          "review_desc": "تفصیل کا جائزہ لیں۔",
          "review_btn_submitting": "جمع کر رہا ہے...",
          "review_btn_submitt": "جمع کرائیں",
          "receibal_amount_whill_applying": "آپ کی قابل وصول رقم (inc VAT)",
        }
      };
}
